### ISSUE TITLE
SSR error with Hero and options in 2.0

### ISSUE THREAD

**Issue by dbrattli** [Fulma/Fulma#207]
I get a runtime error when using Hero options with Fulma (2.0) server side (SSR), e.g:

```fs
Hero.hero [
    Hero.IsMedium
    Hero.IsBold
    ] []
```
Client side (Fable) works fine, but server side I get this error when using options such as `IsMedum` or `IsBold`. Other options such as `Hero.Color IsPrimary` works fine both client and server side.

```
---> (Inner Exception #0) System.ArgumentException: Type 'System.Object' is not an F# union type.
Parameter name: unionType
   at Microsoft.FSharp.Reflection.Impl.checkUnionType(Type unionType, BindingFlags bindingFlags)
   at Microsoft.FSharp.Reflection.FSharpValue.GetUnionFields(Object value, Type unionType, FSharpOption`1 bindingFlags)
   at Fulma.Reflection.getCaseName[T](T case)
   at Fulma.Hero.parseOptions@31-56.Invoke(GenericOptions result, Option option)
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list)
   at Fulma.Common.GenericOptions.Parse[a](FSharpList`1 options, FSharpFunc`2 parser, FSharpOption`1 baseClass, FSharpOption`1 baseProps)
   at Fulma.Hero.hero(FSharpList`1 options, FSharpList`1 children)
   at Shared.View.view(Model model, FSharpFunc`2 dispatch) in /Users/dbrattli/Developer/Github/xyz/src/Shared/View.fs:line 62
   at ServerCode.Templates.index(FSharpOption`1 model) in /Users/dbrattli/Developer/Github/xyz/src/Server/Templates.fs:line 21
   at ServerCode.Pages.home@20.Invoke(Unit unitVar) in /Users/dbrattli/Developer/Github/xyz/src/Server/Pages.fs:line 28
   at FSharp.Control.Tasks.TaskBuilder.run[a](FSharpFunc`2 firstStep) in C:\Users\humbo\source\repos\TaskBuilder.fs\TaskBuilder.fs:line 226
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by MangelMaxime** [comment]
Hello,

are `Hero.IsLarge` and `IsFullheightWithNavbar` working too?

**Comment by dbrattli** [comment]
Had not tried them, but tested now and they are not working either.

**Comment by dbrattli** [comment]
`Hero.CustomClass` is working

**Comment by dbrattli** [comment]
Also tried `Section.section [ Section.IsMedium] []` which is also failing. They were working with Fulma 1.1 that was the previous version I used. Is it something with the compiled name attributes, i.e `[<CompiledName("is-medium")>]` ?

**Comment by MangelMaxime** [comment]
Well Fulma 2.0 introduce is a rewrite of the internal part of Fulma to reduce the bundle size [corresponding PR](https://github.com/Fulma/Fulma/pull/177#issuecomment-458726280). And at the time, I had tested that SSR was working but perhaps I broke something or I missing something in my test...

If you want to take a look at the problem [here](https://github.com/Fulma/Fulma/blob/b2c98d5686f318aefb1fa9af54b285151e5fbb55/src/Fulma/Common.fs#L11-L43) is the code responsible to support SSR.

If you can't or don't have the time, I will try to take a look at this week.

**Comment by dbrattli** [comment]
Thanks for pointing me in the right direction. PR at https://github.com/Fulma/Fulma/pull/208

**Comment by dbrattli** [comment]
Confirming that Fulma (2.0.1) is working for me. Thanks!
