### ISSUE TITLE
Clean install from template

### ISSUE THREAD

**Issue by kierepka** [Fulma/Fulma#274]
```
E:\source\repos\biominds_pl>dotnet fake build -t Watch
Extracted Paket.Restore.targets to: E:\source\repos\biominds_pl\.paket\Paket.Restore.targets (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)
The last restore is still up to date. Nothing left to do.
run Watch
Building project with version: LocalBuild
Shortened DependencyGraph for Target Watch:
<== Watch
   <== YarnInstall
      <== Install
         <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - Install
Group - 3
  - YarnInstall
Group - 4
  - Watch
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0313590
Starting target 'Install'
Starting task 'DotNet:restore': biominds_pl.sln
E:\source\repos\biominds_pl> "C:\Program Files\dotnet\dotnet.EXE"  msbuild /version /nologo (In: false, Out: true, Err: true)
16.8.0.52002
E:\source\repos\biominds_pl> "C:\Program Files\dotnet\dotnet.EXE"  restore biominds_pl.sln /nodeReuse:False "/bl:C:\Users\pc\AppData\Local\Temp\tmp7B31.tmp.binlog" (In: false, Out: false, Err: false)
C:\Program Files\dotnet\sdk\5.0.101\MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\5.0.101\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\5.0.101\dotnet.dll -maxcpuc
ount -target:Restore -verbosity:m /bl:C:\Users\pc\AppData\Local\Temp\tmp7B31.tmp.binlog /nodeReuse:False biominds_pl.sln
  Trwa określanie projektów do przywrócenia...
  Paket version 5.243.0
  Extracted Paket.Restore.targets to: E:\source\repos\biominds_pl\.paket\Paket.Restore.targets (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)
  The last restore is still up to date. Nothing left to do.
  Performance:
   - Runtime: 133 milliseconds
  Paket version 5.243.0
  Starting restore process.
  Performance:
   - Runtime: 685 milliseconds
  Przywrócono element E:\source\repos\biominds_pl\src\biominds_pl.fsproj (w 180 ms).
Finished (Failed) 'DotNet:restore' in 00:00:03.3584414
Finished (Failed) 'Install' in 00:00:03.3618844

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target        Duration
------        --------
Clean         00:00:00.0258594
Install       00:00:03.3614408   (Unsupported log file format. Latest supported version is 8, the log file has version 9.)
YarnInstall   00:00:00           (skipped)
Watch         00:00:00           (skipped)
Total:        00:00:03.5170359
Status:       Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'Install' failed.
-> One or more errors occurred. (Unsupported log file format. Latest supported version is 8, the log file has version 9.)
-> NotSupportedException: Unsupported log file format. Latest supported version is 8, the log file has version 9.
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Hint: Could not find a version in your paket.dependencies file, consider adding 'version 5.241.2' at the top of your dependencies file (E:\source\repos\biominds_pl\paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Hint: The fake-runner has not been updated for at least 6 months. Please consider upgrading to get latest bugfixes, improved suggestions and F# features.
Performance:
 - Cli parsing: 239 milliseconds
 - Packages: 58 milliseconds
   - Creating Runtime Graph: 67 milliseconds
   - Retrieve Assembly List: 616 milliseconds
 - Script compiling: 4 seconds
 - Script analyzing: 228 milliseconds
 - Script running: 3 seconds
 - Script cleanup: 13 milliseconds
 - Runtime: 9 seconds

```

After update to latest tools:

```
E:\source\repos\biominds_pl>dotnet tool restore
Narzędzie "fake-cli" (wersja "5.20.4-alpha.1642") zostało przywrócone. Dostępne polecenia: fake
Narzędzie "paket" (wersja "6.0.0-beta8") zostało przywrócone. Dostępne polecenia: paket
Narzędzie "femto" (wersja "0.9.0") zostało przywrócone. Dostępne polecenia: femto

Przywracanie zakończyło się pomyślnie.

E:\source\repos\biominds_pl>fake.cmd build -t Watch

E:\source\repos\biominds_pl>dotnet tool restore
Narzędzie "fake-cli" (wersja "5.20.4-alpha.1642") zostało przywrócone. Dostępne polecenia: fake
Narzędzie "paket" (wersja "6.0.0-beta8") zostało przywrócone. Dostępne polecenia: paket
Narzędzie "femto" (wersja "0.9.0") zostało przywrócone. Dostępne polecenia: femto

Przywracanie zakończyło się pomyślnie.

E:\source\repos\biominds_pl>dotnet fake build -t Watch
The last restore is still up to date. Nothing left to do.
run Watch
Building project with version: LocalBuild
Shortened DependencyGraph for Target Watch:
<== Watch
   <== YarnInstall
      <== Install
         <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - Install
Group - 3
  - YarnInstall
Group - 4
  - Watch
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0268202
Starting target 'Install'
Starting task 'DotNet:restore': biominds_pl.sln
E:\source\repos\biominds_pl> "C:\Program Files\dotnet\dotnet.EXE"  msbuild /version /nologo (In: false, Out: true, Err: true)
16.8.0.52002
E:\source\repos\biominds_pl> "C:\Program Files\dotnet\dotnet.EXE"  restore biominds_pl.sln /nodeReuse:False "/bl:C:\Users\pc\AppData\Local\Temp\tmp5FA8.tmp.binlog" (In: false, Out: false, Err: false)
C:\Program Files\dotnet\sdk\5.0.101\MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\5.0.101\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\5.0.101\dotnet.dll -maxcpuc
ount -target:Restore -verbosity:m /bl:C:\Users\pc\AppData\Local\Temp\tmp5FA8.tmp.binlog /nodeReuse:False biominds_pl.sln
  Trwa określanie projektów do przywrócenia...
  Paket version 6.0.0-beta8
  The last restore is still up to date. Nothing left to do.
  Total time taken: 0 milliseconds
  Paket version 6.0.0-beta8
  Starting restore process.
  Total time taken: 0 milliseconds
  Przywrócono element E:\source\repos\biominds_pl\src\biominds_pl.fsproj (w 220 ms).
Finished (Failed) 'DotNet:restore' in 00:00:04.0436913
Finished (Failed) 'Install' in 00:00:04.0477281

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target        Duration
------        --------
Clean         00:00:00.0194720
Install       00:00:04.0472199   (Unsupported log file format. Latest supported version is 8, the log file has version 9.)
YarnInstall   00:00:00           (skipped)
Watch         00:00:00           (skipped)
Total:        00:00:04.2177411
Status:       Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'Install' failed.
-> One or more errors occurred. (Unsupported log file format. Latest supported version is 8, the log file has version 9.)
-> NotSupportedException: Unsupported log file format. Latest supported version is 8, the log file has version 9.
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Hint: Could not find a version in your paket.dependencies file, consider adding 'version 5.251.0' at the top of your dependencies file (E:\source\repos\biominds_pl\paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Performance:
 - Cli parsing: 316 milliseconds
 - Packages: 93 milliseconds
 - Script analyzing: 31 milliseconds
 - Script running: 4 seconds
 - Script cleanup: 21 milliseconds
 - Runtime: 5 seconds

````

**Comment by kierepka** [comment]
-v

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target        Duration
------        --------
Clean         00:00:00.0207893
Install       00:00:03.4233923   (Unsupported log file format. Latest supported version is 8, the log file has version 9.)
YarnInstall   00:00:00           (skipped)
Watch         00:00:00           (skipped)
Total:        00:00:03.5320379
Status:       Failure
---------------------------------------------------------------------
saving cache...
Script reported an error, see standard error for details.
Script reported an error:
-> BuildFailedException: Target 'Install' failed.
   StackTrace:
        at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 991
        at Fake.Core.TargetModule.runOrDefault(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1173
        at <StartupCode$build_A86FE970D4111564872FF741D795DCBF45ED7A7E7C8DCDFB836881921FCB0EF4>.$Build$fsx.main@() in E:\source\repos\biominds_pl\build.fsx:line 56
-> One or more errors occurred. (Unsupported log file format. Latest supported version is 8, the log file has version 9.)
-> NotSupportedException: Unsupported log file format. Latest supported version is 8, the log file has version 9.
   StackTrace:
        at Microsoft.Build.Logging.StructuredLogger.BinLogReader.ReadRecordsFromDecompressedStream(Stream decompressedStream)+MoveNext() in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 214
        at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@171.System.Collections.IEnumerator.MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 178
        at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
        at Fake.DotNet.MSBuildBinLog.getErrorsAndWarnings(String binLogFilePath) in D:\a\1\s\src\app\Fake.DotNet.MSBuild\BinLog.fs:line 32
        at Fake.DotNet.MSBuild.handleAfterRun(String command, FSharpOption`1 binLogPath, Int32 exitCode, String project) in D:\a\1\s\src\app\Fake.DotNet.MSBuild\MSBuild.fs:line 738
        at Fake.DotNet.DotNet.restore(FSharpFunc`2 setParams, String project) in D:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 1209
        at Build.clo@20-2.Invoke(TargetParameter _arg2) in E:\source\repos\biominds_pl\build.fsx:line 21
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 300
Performance:
 - Cli parsing: 247 milliseconds
 - Packages: 122 milliseconds
 - Script analyzing: 39 milliseconds
 - Script running: 3 seconds
 - Script cleanup: 16 milliseconds
 - Runtime: 4 seconds
```

**Comment by MangelMaxime** [comment]
Hello @kierepka, 
we saw this error in the past and the fixed was to reinstall the FAKE dependencies from scratch because of some .NET thing^^ (very precise term I know)

Which version of donet are you using? 

- ` dotnet --list-sdks`
- - ` dotnet --list-runtimes`

And which version of the template are you using ?
- `dotnet new -u`

![image](https://user-images.githubusercontent.com/4760796/104207704-afd3f880-5430-11eb-82de-2588da208cd5.png)

**Comment by kierepka** [comment]
Main .net version 5.0.101

Installed:
```
3.1.201 [C:\Program Files\dotnet\sdk]
5.0.100 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
```

```
C:\Users\pc>dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

```
Fable.Template.Fulma.Minimal
    Details:
      NuGetPackageId: Fable.Template.Fulma.Minimal
      Version: 3.1.1
      Author: Maxime Mangel
    Templates:
      Minimal Elmish application with Fulma support (fulma-minimal) F#
    Uninstall Command:
      dotnet new -u Fable.Template.Fulma.Minimal
```

**Comment by MangelMaxime** [comment]
Template version 4 doesn't use FAKE anymore.
